name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # You can specify any Node.js version here

    - name: Install dependencies
      run: npm install

    - name: Configure Git user
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Build the app
      run: npm run build

    - name: Deploy to GitHub Pages
      run: npx gh-pages -d build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
